
language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules
script:
  - yarn pretest
  - yarn run build
env: 
  - SERVER_PORT=3001
  - REACT_APP_API=http://localhost:3001/
  - REACT_APP=http://localhost:3000/
  - DB=mongodb://localhost:27017/hb